redis_clusters:
  - id: cluster1
    host: 127.0.0.1
    port: 7000
    role: reader

  - id: cluster2
    host: 127.0.0.1
    port: 7001
    role: writer

  - id: cluster3
    host: 127.0.0.1
    port: 7002
    role: backup

mongo_db:
  - id: mongo1
    host: "mongodb://localhost:27017"